print("Olá, Pessoal!")
print('Tudo bem?')
print("Linha 3\nLinha 4")
print("Tab1\tTab2\tTab3")
print("01\t105\t1985")
print("C:\\temp")
print("Manoel \"Sabido\" da Silva")
print("Legal 'Simples' Ok")
print('Olha "Dupla" Aqui')
print('Inicio \'Meio\' Fim')
